title: LLM 101
description: The must-knows of LLMs
theme: just-the-docs

just-the-docs:
  toc:
    min_level: 1
    max_level: 2

sass:
  style: compressed


url: https://yildirimcaglar.github.io/teaching

aux_links:
  LLM 101: https://yildirimcaglar.github.io/teaching

plugins:
  - jekyll-default-layout

include:
  - assets/css/just-the-docs.scss

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  note-title:
    color: blue
  summary:
    title: Summary
    color: green
  summary-title:
    color: green
  highlight:
    title: Highlight
    color: yellow
  highlight-title:
    color: yellow
  important:
    title: Important
    color: purple
  important-title:
    color: purple

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

