title: Agentic AI
description: My ramblings on cool agentic AI stuff!
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.5.1

url: https://yildirimcaglar.github.io/teaching

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout


callouts:
  enabled: true
  
