title: Professor Yildirim's Teaching Blog
description: My ramblings on cool AI stuff!
theme: just-the-docs

url: https://yildirimcaglar.github.io/teaching

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout


callouts:
  enabled: true
  
