title: LLM 101
description: The must-knows of LLMs
theme: just-the-docs

url: https://yildirimcaglar.github.io/teaching

aux_links:
  LLM 101: https://yildirimcaglar.github.io/teaching

plugins:
  - jekyll-default-layout

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  note-title:
    color: blue
  summary:
    title: Summary
    color: green
  summary-title:
    color: green
  highlight:
    title: Highlight
    color: yellow
  highlight-title:
    color: yellow
  important:
    title: Important
    color: purple
  important-title:
    color: purple
